// This file was generated by counterfeiter
package fakemetricsaccountant

import (
	"sync"
	"time"

	"github.com/cloudfoundry/hm9000/helpers/metricsaccountant"
	"github.com/cloudfoundry/hm9000/models"
)

type FakeMetricsAccountant struct {
	TrackReceivedHeartbeatsStub        func(metric int) error
	trackReceivedHeartbeatsMutex       sync.RWMutex
	trackReceivedHeartbeatsArgsForCall []struct {
		metric int
	}
	trackReceivedHeartbeatsReturns struct {
		result1 error
	}
	TrackSavedHeartbeatsStub        func(metric int) error
	trackSavedHeartbeatsMutex       sync.RWMutex
	trackSavedHeartbeatsArgsForCall []struct {
		metric int
	}
	trackSavedHeartbeatsReturns struct {
		result1 error
	}
	IncrementSentMessageMetricsStub        func(starts []models.PendingStartMessage, stops []models.PendingStopMessage) error
	incrementSentMessageMetricsMutex       sync.RWMutex
	incrementSentMessageMetricsArgsForCall []struct {
		starts []models.PendingStartMessage
		stops  []models.PendingStopMessage
	}
	incrementSentMessageMetricsReturns struct {
		result1 error
	}
	TrackDesiredStateSyncTimeStub        func(dt time.Duration) error
	trackDesiredStateSyncTimeMutex       sync.RWMutex
	trackDesiredStateSyncTimeArgsForCall []struct {
		dt time.Duration
	}
	trackDesiredStateSyncTimeReturns struct {
		result1 error
	}
	TrackActualStateListenerStoreUsageFractionStub        func(usage float64) error
	trackActualStateListenerStoreUsageFractionMutex       sync.RWMutex
	trackActualStateListenerStoreUsageFractionArgsForCall []struct {
		usage float64
	}
	trackActualStateListenerStoreUsageFractionReturns struct {
		result1 error
	}
	GetMetricsStub        func() (map[string]float64, error)
	getMetricsMutex       sync.RWMutex
	getMetricsArgsForCall []struct{}
	getMetricsReturns struct {
		result1 map[string]float64
		result2 error
	}
}

func (fake *FakeMetricsAccountant) TrackReceivedHeartbeats(metric int) error {
	fake.trackReceivedHeartbeatsMutex.Lock()
	fake.trackReceivedHeartbeatsArgsForCall = append(fake.trackReceivedHeartbeatsArgsForCall, struct {
		metric int
	}{metric})
	fake.trackReceivedHeartbeatsMutex.Unlock()
	if fake.TrackReceivedHeartbeatsStub != nil {
		return fake.TrackReceivedHeartbeatsStub(metric)
	} else {
		return fake.trackReceivedHeartbeatsReturns.result1
	}
}

func (fake *FakeMetricsAccountant) TrackReceivedHeartbeatsCallCount() int {
	fake.trackReceivedHeartbeatsMutex.RLock()
	defer fake.trackReceivedHeartbeatsMutex.RUnlock()
	return len(fake.trackReceivedHeartbeatsArgsForCall)
}

func (fake *FakeMetricsAccountant) TrackReceivedHeartbeatsArgsForCall(i int) int {
	fake.trackReceivedHeartbeatsMutex.RLock()
	defer fake.trackReceivedHeartbeatsMutex.RUnlock()
	return fake.trackReceivedHeartbeatsArgsForCall[i].metric
}

func (fake *FakeMetricsAccountant) TrackReceivedHeartbeatsReturns(result1 error) {
	fake.TrackReceivedHeartbeatsStub = nil
	fake.trackReceivedHeartbeatsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMetricsAccountant) TrackSavedHeartbeats(metric int) error {
	fake.trackSavedHeartbeatsMutex.Lock()
	fake.trackSavedHeartbeatsArgsForCall = append(fake.trackSavedHeartbeatsArgsForCall, struct {
		metric int
	}{metric})
	fake.trackSavedHeartbeatsMutex.Unlock()
	if fake.TrackSavedHeartbeatsStub != nil {
		return fake.TrackSavedHeartbeatsStub(metric)
	} else {
		return fake.trackSavedHeartbeatsReturns.result1
	}
}

func (fake *FakeMetricsAccountant) TrackSavedHeartbeatsCallCount() int {
	fake.trackSavedHeartbeatsMutex.RLock()
	defer fake.trackSavedHeartbeatsMutex.RUnlock()
	return len(fake.trackSavedHeartbeatsArgsForCall)
}

func (fake *FakeMetricsAccountant) TrackSavedHeartbeatsArgsForCall(i int) int {
	fake.trackSavedHeartbeatsMutex.RLock()
	defer fake.trackSavedHeartbeatsMutex.RUnlock()
	return fake.trackSavedHeartbeatsArgsForCall[i].metric
}

func (fake *FakeMetricsAccountant) TrackSavedHeartbeatsReturns(result1 error) {
	fake.TrackSavedHeartbeatsStub = nil
	fake.trackSavedHeartbeatsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMetricsAccountant) IncrementSentMessageMetrics(starts []models.PendingStartMessage, stops []models.PendingStopMessage) error {
	fake.incrementSentMessageMetricsMutex.Lock()
	fake.incrementSentMessageMetricsArgsForCall = append(fake.incrementSentMessageMetricsArgsForCall, struct {
		starts []models.PendingStartMessage
		stops  []models.PendingStopMessage
	}{starts, stops})
	fake.incrementSentMessageMetricsMutex.Unlock()
	if fake.IncrementSentMessageMetricsStub != nil {
		return fake.IncrementSentMessageMetricsStub(starts, stops)
	} else {
		return fake.incrementSentMessageMetricsReturns.result1
	}
}

func (fake *FakeMetricsAccountant) IncrementSentMessageMetricsCallCount() int {
	fake.incrementSentMessageMetricsMutex.RLock()
	defer fake.incrementSentMessageMetricsMutex.RUnlock()
	return len(fake.incrementSentMessageMetricsArgsForCall)
}

func (fake *FakeMetricsAccountant) IncrementSentMessageMetricsArgsForCall(i int) ([]models.PendingStartMessage, []models.PendingStopMessage) {
	fake.incrementSentMessageMetricsMutex.RLock()
	defer fake.incrementSentMessageMetricsMutex.RUnlock()
	return fake.incrementSentMessageMetricsArgsForCall[i].starts, fake.incrementSentMessageMetricsArgsForCall[i].stops
}

func (fake *FakeMetricsAccountant) IncrementSentMessageMetricsReturns(result1 error) {
	fake.IncrementSentMessageMetricsStub = nil
	fake.incrementSentMessageMetricsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMetricsAccountant) TrackDesiredStateSyncTime(dt time.Duration) error {
	fake.trackDesiredStateSyncTimeMutex.Lock()
	fake.trackDesiredStateSyncTimeArgsForCall = append(fake.trackDesiredStateSyncTimeArgsForCall, struct {
		dt time.Duration
	}{dt})
	fake.trackDesiredStateSyncTimeMutex.Unlock()
	if fake.TrackDesiredStateSyncTimeStub != nil {
		return fake.TrackDesiredStateSyncTimeStub(dt)
	} else {
		return fake.trackDesiredStateSyncTimeReturns.result1
	}
}

func (fake *FakeMetricsAccountant) TrackDesiredStateSyncTimeCallCount() int {
	fake.trackDesiredStateSyncTimeMutex.RLock()
	defer fake.trackDesiredStateSyncTimeMutex.RUnlock()
	return len(fake.trackDesiredStateSyncTimeArgsForCall)
}

func (fake *FakeMetricsAccountant) TrackDesiredStateSyncTimeArgsForCall(i int) time.Duration {
	fake.trackDesiredStateSyncTimeMutex.RLock()
	defer fake.trackDesiredStateSyncTimeMutex.RUnlock()
	return fake.trackDesiredStateSyncTimeArgsForCall[i].dt
}

func (fake *FakeMetricsAccountant) TrackDesiredStateSyncTimeReturns(result1 error) {
	fake.TrackDesiredStateSyncTimeStub = nil
	fake.trackDesiredStateSyncTimeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMetricsAccountant) TrackActualStateListenerStoreUsageFraction(usage float64) error {
	fake.trackActualStateListenerStoreUsageFractionMutex.Lock()
	fake.trackActualStateListenerStoreUsageFractionArgsForCall = append(fake.trackActualStateListenerStoreUsageFractionArgsForCall, struct {
		usage float64
	}{usage})
	fake.trackActualStateListenerStoreUsageFractionMutex.Unlock()
	if fake.TrackActualStateListenerStoreUsageFractionStub != nil {
		return fake.TrackActualStateListenerStoreUsageFractionStub(usage)
	} else {
		return fake.trackActualStateListenerStoreUsageFractionReturns.result1
	}
}

func (fake *FakeMetricsAccountant) TrackActualStateListenerStoreUsageFractionCallCount() int {
	fake.trackActualStateListenerStoreUsageFractionMutex.RLock()
	defer fake.trackActualStateListenerStoreUsageFractionMutex.RUnlock()
	return len(fake.trackActualStateListenerStoreUsageFractionArgsForCall)
}

func (fake *FakeMetricsAccountant) TrackActualStateListenerStoreUsageFractionArgsForCall(i int) float64 {
	fake.trackActualStateListenerStoreUsageFractionMutex.RLock()
	defer fake.trackActualStateListenerStoreUsageFractionMutex.RUnlock()
	return fake.trackActualStateListenerStoreUsageFractionArgsForCall[i].usage
}

func (fake *FakeMetricsAccountant) TrackActualStateListenerStoreUsageFractionReturns(result1 error) {
	fake.TrackActualStateListenerStoreUsageFractionStub = nil
	fake.trackActualStateListenerStoreUsageFractionReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMetricsAccountant) GetMetrics() (map[string]float64, error) {
	fake.getMetricsMutex.Lock()
	fake.getMetricsArgsForCall = append(fake.getMetricsArgsForCall, struct{}{})
	fake.getMetricsMutex.Unlock()
	if fake.GetMetricsStub != nil {
		return fake.GetMetricsStub()
	} else {
		return fake.getMetricsReturns.result1, fake.getMetricsReturns.result2
	}
}

func (fake *FakeMetricsAccountant) GetMetricsCallCount() int {
	fake.getMetricsMutex.RLock()
	defer fake.getMetricsMutex.RUnlock()
	return len(fake.getMetricsArgsForCall)
}

func (fake *FakeMetricsAccountant) GetMetricsReturns(result1 map[string]float64, result2 error) {
	fake.GetMetricsStub = nil
	fake.getMetricsReturns = struct {
		result1 map[string]float64
		result2 error
	}{result1, result2}
}

var _ metricsaccountant.MetricsAccountant = new(FakeMetricsAccountant)
